# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cube\PycharmProjects\malysh\M_Dawson_Home_Work\Chapter_2\QtPy5\challenge_QtPy2.3.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1102, 628)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1403, 837))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_q = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_q.setFont(font)
        self.label_q.setObjectName("label_q")
        self.verticalLayout_7.addWidget(self.label_q)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_0 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_0.setFont(font)
        self.label_0.setObjectName("label_0")
        self.verticalLayout_2.addWidget(self.label_0)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_0 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_0.setMaximum(1000000)
        self.horizontalSlider_0.setSingleStep(5000)
        self.horizontalSlider_0.setPageStep(20000)
        self.horizontalSlider_0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_0.setObjectName("horizontalSlider_0")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_0)
        self.spinBox_0 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_0.setMaximum(1000000)
        self.spinBox_0.setSingleStep(5000)
        self.spinBox_0.setProperty("value", 0)
        self.spinBox_0.setObjectName("spinBox_0")
        self.horizontalLayout_2.addWidget(self.spinBox_0)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_1.setMaximum(100)
        self.horizontalSlider_1.setProperty("value", 13)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.horizontalLayout.addWidget(self.horizontalSlider_1)
        self.spinBox_1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_1.setMaximum(100)
        self.spinBox_1.setProperty("value", 13)
        self.spinBox_1.setObjectName("spinBox_1")
        self.horizontalLayout.addWidget(self.spinBox_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 5)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setProperty("value", 5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_3.setMaximum(5)
        self.horizontalSlider_3.setPageStep(2)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_4.setMaximum(2)
        self.horizontalSlider_4.setPageStep(2)
        self.horizontalSlider_4.setProperty("value", 1)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalLayout_5.addWidget(self.horizontalSlider_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.label_q_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_1.setFont(font)
        self.label_q_1.setObjectName("label_q_1")
        self.verticalLayout_5.addWidget(self.label_q_1)
        spacerItem = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_img = QtWidgets.QLabel(self.layoutWidget)
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("data/cars/light.png"))
        self.label_img.setObjectName("label_img")
        self.verticalLayout_8.addWidget(self.label_img)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Form)
        self.horizontalSlider_1.valueChanged['int'].connect(self.spinBox_1.setValue)
        self.spinBox_1.valueChanged['int'].connect(self.horizontalSlider_1.setValue)
        self.horizontalSlider_0.valueChanged['int'].connect(self.spinBox_0.setValue)
        self.horizontalSlider_2.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.spinBox_0.valueChanged['int'].connect(self.horizontalSlider_0.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.horizontalSlider_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_q.setText(_translate("Form", "Cтоимость автомобиля?"))
        self.label_0.setText(_translate("Form", "Цена :"))
        self.label_1.setText(_translate("Form", "Налог :"))
        self.label_2.setText(_translate("Form", "Регистрационный сбор :"))
        self.label_3.setText(_translate("Form", "Агентский сбор : 1000"))
        self.label_4.setText(_translate("Form", "Доставка обычная : 5000"))
        self.label_q_1.setText(_translate("Form", "Итого: "))

