# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cube\PycharmProjects\malysh\M_Dawson_Home_Work\Chapter_3\QtPy5\challenge_QtPy3_3_4.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_img_0 = QtWidgets.QLabel(self.tab_0)
        self.label_img_0.setText("")
        self.label_img_0.setPixmap(QtGui.QPixmap("data/doom/death13.png"))
        self.label_img_0.setObjectName("label_img_0")
        self.gridLayout.addWidget(self.label_img_0, 0, 0, 1, 1)
        self.textEdit_0 = QtWidgets.QTextEdit(self.tab_0)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit_0.setFont(font)
        self.textEdit_0.setObjectName("textEdit_0")
        self.gridLayout.addWidget(self.textEdit_0, 0, 1, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.tab_0)
        self.label_0.setObjectName("label_0")
        self.gridLayout.addWidget(self.label_0, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_0 = QtWidgets.QLineEdit(self.tab_0)
        self.lineEdit_0.setObjectName("lineEdit_0")
        self.horizontalLayout.addWidget(self.lineEdit_0)
        self.pushButton_1 = QtWidgets.QPushButton(self.tab_0)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.tab_0)
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label__img_1 = QtWidgets.QLabel(self.tab_1)
        self.label__img_1.setText("")
        self.label__img_1.setPixmap(QtGui.QPixmap("data/doom/robot07.png"))
        self.label__img_1.setObjectName("label__img_1")
        self.gridLayout_2.addWidget(self.label__img_1, 0, 0, 1, 1)
        self.textEdit_1 = QtWidgets.QTextEdit(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit_1.setFont(font)
        self.textEdit_1.setObjectName("textEdit_1")
        self.gridLayout_2.addWidget(self.textEdit_1, 0, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.tab_1)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_2.addWidget(self.lineEdit_1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton_0)
        MainWindow.setTabOrder(self.pushButton_0, self.lineEdit_0)
        MainWindow.setTabOrder(self.lineEdit_0, self.pushButton_1)
        MainWindow.setTabOrder(self.pushButton_1, self.textEdit_0)
        MainWindow.setTabOrder(self.textEdit_0, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.lineEdit_1)
        MainWindow.setTabOrder(self.lineEdit_1, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.textEdit_1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_0.setText(_translate("MainWindow", "Смертный впиши цифру"))
        self.pushButton_1.setText(_translate("MainWindow", "Сказать ответ"))
        self.pushButton_0.setText(_translate("MainWindow", "Начать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "Отгадай число"))
        self.label_1.setText(_translate("MainWindow", "Впишите: больше, меньше или верно"))
        self.pushButton_3.setText(_translate("MainWindow", "Наставить"))
        self.pushButton_2.setText(_translate("MainWindow", "Начать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Загадай число"))

